flags: {}
nix:
  enable: false
  shell-file: shell.nix
extra-package-dbs: []
packages:
- location: .
- location:
    git: git@github.com:MatrixAI/haskell-multihash.git
    commit: 55f82094ec1cd787bbf969fc7b07f9419c891efa
  extra-dep: true
extra-deps:
- base58-bytestring-0.1.0
resolver: lts-8.15
