flags: {}
nix:
  enable: false
  shell-file: shell.nix
extra-package-dbs: []
packages:
- location: .
- location:
    git: git@github.com:MatrixAI/haskell-multihash.git
    commit: abd0cffac2b66e658e9345437a03d31fe7779ddc 
  extra-dep: true
extra-deps:
- base58-bytestring-0.1.0
resolver: lts-9.4
