flags: {}
nix:
  enable: false
  shell-file: shell.nix
extra-package-dbs: []
packages:
- location: .
- location:
    git: git@github.com:MatrixAI/haskell-multihash.git
    commit: b604fab178d24e3fcb5b638e5bcba6b2e9265fb6 
  extra-dep: true
extra-deps:
- base58-bytestring-0.1.0
resolver: lts-9.0
