resolver: lts-11.6
packages:
  - location: .
  - location:
      git: git@github.com:MatrixAI/hs-multihash.git
      commit: a150c80297aad40938743aa9266b64fdd03ab704
    extra-dep: true
extra-deps:
  - base58-bytestring-0.1.0
  - sandi-0.4.2
