flags: {}
nix:
  enable: false
  shell-file: shell.nix
extra-package-dbs: []
packages:
- location: .
- location:
    git: git@github.com:MatrixAI/haskell-multihash.git
    commit: 0c95cb0efb72c6d3dc1cd1e092be75f5a0f78210 
  extra-dep: true
extra-deps:
- base58-bytestring-0.1.0
resolver: lts-9.0
